using System.Drawing;
using System.Windows.Forms;

namespace JCGAttendanceSystem.Forms.Authentication
{
    partial class LoginForm
    {
        private TableLayoutPanel _rootLayout;
        private Panel _brandPanel;
        private Label _brandMarkLabel;
        private Label _brandNameLabel;
        private Label _brandDescriptionLabel;
        private TableLayoutPanel _loginHost;
        private Panel _loginCard;
        private Label _welcomeLabel;
        private Label _subtitleLabel;
        private Label _usernameLabel;
        private TextBox _username;
        private Label _passwordLabel;
        private TextBox _password;
        private CheckBox _showPassword;
        private Label _error;
        private Button _signInButton;
        private Label _storageNoteLabel;

        private void InitializeComponent()
        {
            this._rootLayout = new TableLayoutPanel();
            this._brandPanel = new Panel();
            this._brandMarkLabel = new Label();
            this._brandNameLabel = new Label();
            this._brandDescriptionLabel = new Label();
            this._loginHost = new TableLayoutPanel();
            this._loginCard = new Panel();
            this._welcomeLabel = new Label();
            this._subtitleLabel = new Label();
            this._usernameLabel = new Label();
            this._username = new TextBox();
            this._passwordLabel = new Label();
            this._password = new TextBox();
            this._showPassword = new CheckBox();
            this._error = new Label();
            this._signInButton = new Button();
            this._storageNoteLabel = new Label();
            this.SuspendLayout();
            // root layout
            this._rootLayout.BackColor = Color.FromArgb(244, 247, 250);
            this._rootLayout.ColumnCount = 2;
            this._rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 40F));
            this._rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 60F));
            this._rootLayout.Dock = DockStyle.Fill;
            this._rootLayout.RowCount = 1;
            this._rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            // brand panel
            this._brandPanel.BackColor = Color.FromArgb(11, 31, 51);
            this._brandPanel.Controls.Add(this._brandDescriptionLabel);
            this._brandPanel.Controls.Add(this._brandNameLabel);
            this._brandPanel.Controls.Add(this._brandMarkLabel);
            this._brandPanel.Dock = DockStyle.Fill;
            this._brandPanel.Padding = new Padding(56);
            this._brandMarkLabel.AutoSize = true;
            this._brandMarkLabel.Font = new Font("Segoe UI", 32F, FontStyle.Bold);
            this._brandMarkLabel.ForeColor = Color.White;
            this._brandMarkLabel.Location = new Point(56, 188);
            this._brandMarkLabel.Text = "JCG";
            this._brandNameLabel.AutoSize = true;
            this._brandNameLabel.Font = new Font("Segoe UI", 15F, FontStyle.Bold);
            this._brandNameLabel.ForeColor = Color.FromArgb(174, 214, 241);
            this._brandNameLabel.Location = new Point(58, 240);
            this._brandNameLabel.Text = "ATTENDANCE SYSTEM";
            this._brandDescriptionLabel.Font = new Font("Segoe UI", 10.5F);
            this._brandDescriptionLabel.ForeColor = Color.FromArgb(210, 220, 230);
            this._brandDescriptionLabel.Location = new Point(59, 296);
            this._brandDescriptionLabel.Size = new Size(320, 92);
            this._brandDescriptionLabel.Text = "Secure student attendance management with a workflow ready for future RFID hardware integration.";
            // protected login host: keeps the card centered and prevents TableLayoutPanel from collapsing it
            this._loginHost.BackColor = Color.FromArgb(244, 247, 250);
            this._loginHost.ColumnCount = 3;
            this._loginHost.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            this._loginHost.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 460F));
            this._loginHost.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            this._loginHost.Dock = DockStyle.Fill;
            this._loginHost.RowCount = 3;
            this._loginHost.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
            this._loginHost.RowStyles.Add(new RowStyle(SizeType.Absolute, 500F));
            this._loginHost.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
            // login card
            this._loginCard.BackColor = Color.White;
            this._loginCard.BorderStyle = BorderStyle.FixedSingle;
            this._loginCard.Dock = DockStyle.Fill;
            this._loginCard.Margin = new Padding(0);
            this._welcomeLabel.AutoSize = true;
            this._welcomeLabel.Font = new Font("Segoe UI", 23F, FontStyle.Bold);
            this._welcomeLabel.ForeColor = Color.FromArgb(31, 41, 55);
            this._welcomeLabel.Location = new Point(46, 44);
            this._welcomeLabel.Text = "Welcome back";
            this._subtitleLabel.Font = new Font("Segoe UI", 9.5F);
            this._subtitleLabel.ForeColor = Color.FromArgb(107, 114, 128);
            this._subtitleLabel.Location = new Point(49, 94);
            this._subtitleLabel.Size = new Size(360, 42);
            this._subtitleLabel.Text = "Sign in with your administrator or staff account.";
            this._usernameLabel.AutoSize = true;
            this._usernameLabel.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            this._usernameLabel.ForeColor = Color.FromArgb(31, 41, 55);
            this._usernameLabel.Location = new Point(49, 151);
            this._usernameLabel.Text = "Username";
            this._username.BorderStyle = BorderStyle.FixedSingle;
            this._username.Font = new Font("Segoe UI", 11F);
            this._username.Location = new Point(50, 177);
            this._username.Size = new Size(360, 32);
            this._username.TabIndex = 0;
            this._passwordLabel.AutoSize = true;
            this._passwordLabel.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            this._passwordLabel.ForeColor = Color.FromArgb(31, 41, 55);
            this._passwordLabel.Location = new Point(49, 229);
            this._passwordLabel.Text = "Password";
            this._password.BorderStyle = BorderStyle.FixedSingle;
            this._password.Font = new Font("Segoe UI", 11F);
            this._password.Location = new Point(50, 255);
            this._password.Size = new Size(360, 32);
            this._password.UseSystemPasswordChar = true;
            this._password.TabIndex = 1;
            this._showPassword.AutoSize = true;
            this._showPassword.Font = new Font("Segoe UI", 8.5F);
            this._showPassword.ForeColor = Color.FromArgb(107, 114, 128);
            this._showPassword.Location = new Point(50, 298);
            this._showPassword.Text = "Show password";
            this._showPassword.TabIndex = 2;
            this._showPassword.CheckedChanged += new System.EventHandler(this.ShowPassword_CheckedChanged);
            this._error.Font = new Font("Segoe UI", 8.8F);
            this._error.ForeColor = Color.FromArgb(198, 40, 40);
            this._error.Location = new Point(50, 327);
            this._error.Size = new Size(360, 38);
            this._signInButton.BackColor = Color.FromArgb(30, 136, 229);
            this._signInButton.Cursor = Cursors.Hand;
            this._signInButton.FlatAppearance.BorderSize = 0;
            this._signInButton.FlatStyle = FlatStyle.Flat;
            this._signInButton.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            this._signInButton.ForeColor = Color.White;
            this._signInButton.Location = new Point(50, 370);
            this._signInButton.Size = new Size(360, 46);
            this._signInButton.Text = "Sign In";
            this._signInButton.TabIndex = 3;
            this._signInButton.Click += new System.EventHandler(this.SignIn_Click);
            this._storageNoteLabel.Font = new Font("Segoe UI", 8.3F);
            this._storageNoteLabel.ForeColor = Color.FromArgb(107, 114, 128);
            this._storageNoteLabel.Location = new Point(50, 438);
            this._storageNoteLabel.Size = new Size(360, 40);
            this._storageNoteLabel.Text = "Runtime data is stored securely in your Windows local application-data folder.";
            this._loginCard.Controls.Add(this._storageNoteLabel);
            this._loginCard.Controls.Add(this._signInButton);
            this._loginCard.Controls.Add(this._error);
            this._loginCard.Controls.Add(this._showPassword);
            this._loginCard.Controls.Add(this._password);
            this._loginCard.Controls.Add(this._passwordLabel);
            this._loginCard.Controls.Add(this._username);
            this._loginCard.Controls.Add(this._usernameLabel);
            this._loginCard.Controls.Add(this._subtitleLabel);
            this._loginCard.Controls.Add(this._welcomeLabel);
            this._loginHost.Controls.Add(this._loginCard, 1, 1);
            this._rootLayout.Controls.Add(this._brandPanel, 0, 0);
            this._rootLayout.Controls.Add(this._loginHost, 1, 0);
            this.AcceptButton = this._signInButton;
            this.AutoScaleDimensions = new SizeF(7F, 15F);
            this.AutoScaleMode = AutoScaleMode.Font;
            this.BackColor = Color.FromArgb(244, 247, 250);
            this.ClientSize = new Size(1120, 700);
            this.Controls.Add(this._rootLayout);
            this.MinimumSize = new Size(1000, 640);
            this.Name = "LoginForm";
            this.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "JCG Attendance System - Sign In";
            this.ResumeLayout(false);
        }
    }
}
