using System.Drawing;
using System.Windows.Forms;

namespace JCGAttendanceSystem.Forms.Settings
{
    partial class SettingsForm
    {
        private FlowLayoutPanel _rootFlow;
        private Panel _accountPanel;
        private Label _accountTitle;
        private Label _accountSubtitle;
        private Button _changePasswordButton;
        private Panel _applicationPanel;
        private Label _applicationTitle;
        private Label _applicationSubtitle;
        private Label _organizationLabel;
        private TextBox _organization;
        private Button _saveOrganizationButton;
        private Label _databasePathLabel;
        private Panel _adminToolsPanel;
        private Label _adminTitle;
        private Label _adminSubtitle;
        private Button _userManagementButton;
        private Button _auditButton;
        private Button _backupButton;
        private Button _restoreButton;
        private Button _legacyButton;

        private void InitializeComponent()
        {
            this._rootFlow = new FlowLayoutPanel();
            this._accountPanel = new Panel();
            this._accountTitle = new Label();
            this._accountSubtitle = new Label();
            this._changePasswordButton = new Button();
            this._applicationPanel = new Panel();
            this._applicationTitle = new Label();
            this._applicationSubtitle = new Label();
            this._organizationLabel = new Label();
            this._organization = new TextBox();
            this._saveOrganizationButton = new Button();
            this._databasePathLabel = new Label();
            this._adminToolsPanel = new Panel();
            this._adminTitle = new Label();
            this._adminSubtitle = new Label();
            this._userManagementButton = new Button();
            this._auditButton = new Button();
            this._backupButton = new Button();
            this._restoreButton = new Button();
            this._legacyButton = new Button();
            this.SuspendLayout();
            this._rootFlow.AutoScroll = true;
            this._rootFlow.BackColor = Color.FromArgb(244, 247, 250);
            this._rootFlow.Dock = DockStyle.Fill;
            this._rootFlow.FlowDirection = FlowDirection.TopDown;
            this._rootFlow.Name = "_rootFlow";
            this._rootFlow.WrapContents = false;
            // Account section
            this._accountPanel.BackColor = Color.White;
            this._accountPanel.BorderStyle = BorderStyle.FixedSingle;
            this._accountPanel.Margin = new Padding(0, 0, 0, 16);
            this._accountPanel.Name = "_accountPanel";
            this._accountPanel.Size = new Size(980, 164);
            this._accountTitle.AutoSize = true;
            this._accountTitle.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            this._accountTitle.ForeColor = Color.FromArgb(31, 41, 55);
            this._accountTitle.Location = new Point(20, 18);
            this._accountTitle.Text = "Account";
            this._accountSubtitle.AutoSize = true;
            this._accountSubtitle.Font = new Font("Segoe UI", 9F);
            this._accountSubtitle.ForeColor = Color.FromArgb(107, 114, 128);
            this._accountSubtitle.Location = new Point(22, 52);
            this._accountSubtitle.Text = "Manage your signed-in account.";
            this._changePasswordButton.BackColor = Color.White;
            this._changePasswordButton.FlatAppearance.BorderColor = Color.FromArgb(210, 218, 226);
            this._changePasswordButton.FlatStyle = FlatStyle.Flat;
            this._changePasswordButton.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            this._changePasswordButton.ForeColor = Color.FromArgb(31, 41, 55);
            this._changePasswordButton.Location = new Point(20, 86);
            this._changePasswordButton.Size = new Size(165, 42);
            this._changePasswordButton.Text = "Change Password";
            this._accountPanel.Controls.Add(this._changePasswordButton);
            this._accountPanel.Controls.Add(this._accountSubtitle);
            this._accountPanel.Controls.Add(this._accountTitle);
            // Application section
            this._applicationPanel.BackColor = Color.White;
            this._applicationPanel.BorderStyle = BorderStyle.FixedSingle;
            this._applicationPanel.Margin = new Padding(0, 0, 0, 16);
            this._applicationPanel.Name = "_applicationPanel";
            this._applicationPanel.Size = new Size(980, 196);
            this._applicationTitle.AutoSize = true;
            this._applicationTitle.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            this._applicationTitle.ForeColor = Color.FromArgb(31, 41, 55);
            this._applicationTitle.Location = new Point(20, 18);
            this._applicationTitle.Text = "Application";
            this._applicationSubtitle.AutoSize = true;
            this._applicationSubtitle.Font = new Font("Segoe UI", 9F);
            this._applicationSubtitle.ForeColor = Color.FromArgb(107, 114, 128);
            this._applicationSubtitle.Location = new Point(22, 52);
            this._applicationSubtitle.Text = "Local data and display settings.";
            this._organizationLabel.AutoSize = true;
            this._organizationLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            this._organizationLabel.ForeColor = Color.FromArgb(31, 41, 55);
            this._organizationLabel.Location = new Point(20, 82);
            this._organizationLabel.Text = "Organization / system display name";
            this._organization.Font = new Font("Segoe UI", 10F);
            this._organization.Location = new Point(23, 108);
            this._organization.Size = new Size(360, 30);
            this._saveOrganizationButton.BackColor = Color.White;
            this._saveOrganizationButton.FlatAppearance.BorderColor = Color.FromArgb(210, 218, 226);
            this._saveOrganizationButton.FlatStyle = FlatStyle.Flat;
            this._saveOrganizationButton.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            this._saveOrganizationButton.ForeColor = Color.FromArgb(31, 41, 55);
            this._saveOrganizationButton.Location = new Point(398, 104);
            this._saveOrganizationButton.Size = new Size(110, 38);
            this._saveOrganizationButton.Text = "Save Name";
            this._saveOrganizationButton.Click += new System.EventHandler(this.SaveOrganization_Click);
            this._databasePathLabel.Font = new Font("Segoe UI", 8.5F);
            this._databasePathLabel.ForeColor = Color.FromArgb(107, 114, 128);
            this._databasePathLabel.Location = new Point(22, 156);
            this._databasePathLabel.Size = new Size(900, 30);
            this._applicationPanel.Controls.Add(this._databasePathLabel);
            this._applicationPanel.Controls.Add(this._saveOrganizationButton);
            this._applicationPanel.Controls.Add(this._organization);
            this._applicationPanel.Controls.Add(this._organizationLabel);
            this._applicationPanel.Controls.Add(this._applicationSubtitle);
            this._applicationPanel.Controls.Add(this._applicationTitle);
            // Admin tools
            this._adminToolsPanel.BackColor = Color.White;
            this._adminToolsPanel.BorderStyle = BorderStyle.FixedSingle;
            this._adminToolsPanel.Margin = new Padding(0, 0, 0, 16);
            this._adminToolsPanel.Name = "_adminToolsPanel";
            this._adminToolsPanel.Size = new Size(980, 180);
            this._adminTitle.AutoSize = true;
            this._adminTitle.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            this._adminTitle.ForeColor = Color.FromArgb(31, 41, 55);
            this._adminTitle.Location = new Point(20, 18);
            this._adminTitle.Text = "Administrator Tools";
            this._adminSubtitle.AutoSize = true;
            this._adminSubtitle.Font = new Font("Segoe UI", 9F);
            this._adminSubtitle.ForeColor = Color.FromArgb(107, 114, 128);
            this._adminSubtitle.Location = new Point(22, 52);
            this._adminSubtitle.Text = "Manage staff accounts, review audit history, and protect or migrate system data.";
            this._userManagementButton.BackColor = Color.FromArgb(30, 136, 229);
            this._userManagementButton.FlatAppearance.BorderSize = 0;
            this._userManagementButton.FlatStyle = FlatStyle.Flat;
            this._userManagementButton.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            this._userManagementButton.ForeColor = Color.White;
            this._userManagementButton.Location = new Point(20, 88);
            this._userManagementButton.Size = new Size(150, 42);
            this._userManagementButton.Text = "User Management";
            this._auditButton.BackColor = Color.White;
            this._auditButton.FlatAppearance.BorderColor = Color.FromArgb(210, 218, 226);
            this._auditButton.FlatStyle = FlatStyle.Flat;
            this._auditButton.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            this._auditButton.Location = new Point(182, 88);
            this._auditButton.Size = new Size(120, 42);
            this._auditButton.Text = "Audit Log";
            this._backupButton.BackColor = Color.White;
            this._backupButton.FlatAppearance.BorderColor = Color.FromArgb(210, 218, 226);
            this._backupButton.FlatStyle = FlatStyle.Flat;
            this._backupButton.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            this._backupButton.Location = new Point(314, 88);
            this._backupButton.Size = new Size(140, 42);
            this._backupButton.Text = "Backup Database";
            this._backupButton.Click += new System.EventHandler(this.Backup_Click);
            this._restoreButton.BackColor = Color.White;
            this._restoreButton.FlatAppearance.BorderColor = Color.FromArgb(210, 218, 226);
            this._restoreButton.FlatStyle = FlatStyle.Flat;
            this._restoreButton.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            this._restoreButton.Location = new Point(466, 88);
            this._restoreButton.Size = new Size(140, 42);
            this._restoreButton.Text = "Restore Database";
            this._restoreButton.Click += new System.EventHandler(this.Restore_Click);
            this._legacyButton.BackColor = Color.White;
            this._legacyButton.FlatAppearance.BorderColor = Color.FromArgb(210, 218, 226);
            this._legacyButton.FlatStyle = FlatStyle.Flat;
            this._legacyButton.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            this._legacyButton.Location = new Point(618, 88);
            this._legacyButton.Size = new Size(150, 42);
            this._legacyButton.Text = "Import Legacy Data";
            this._legacyButton.Click += new System.EventHandler(this.Legacy_Click);
            this._adminToolsPanel.Controls.Add(this._legacyButton);
            this._adminToolsPanel.Controls.Add(this._restoreButton);
            this._adminToolsPanel.Controls.Add(this._backupButton);
            this._adminToolsPanel.Controls.Add(this._auditButton);
            this._adminToolsPanel.Controls.Add(this._userManagementButton);
            this._adminToolsPanel.Controls.Add(this._adminSubtitle);
            this._adminToolsPanel.Controls.Add(this._adminTitle);
            this._rootFlow.Controls.Add(this._accountPanel);
            this._rootFlow.Controls.Add(this._applicationPanel);
            this._rootFlow.Controls.Add(this._adminToolsPanel);
            this.AutoScaleDimensions = new SizeF(7F, 15F);
            this.AutoScaleMode = AutoScaleMode.Font;
            this.AutoScroll = true;
            this.BackColor = Color.FromArgb(244, 247, 250);
            this.Controls.Add(this._rootFlow);
            this.Name = "SettingsForm";
            this.Text = "Settings";
            this.ResumeLayout(false);
        }
    }
}
