using System.Drawing;
using System.Windows.Forms;

namespace JCGAttendanceSystem.Forms.Settings
{
    partial class UserEditorForm
    {
        private Label _headingLabel; private Label _subtitleLabel; private Label _usernameLabel; private TextBox _username; private Label _passwordLabel; private TextBox _password; private Label _confirmLabel; private TextBox _confirm; private Label _error; private Button _saveButton;
        private void InitializeComponent(){_headingLabel=new Label();_subtitleLabel=new Label();_usernameLabel=new Label();_username=new TextBox();_passwordLabel=new Label();_password=new TextBox();_confirmLabel=new Label();_confirm=new TextBox();_error=new Label();_saveButton=new Button();SuspendLayout();BackColor=Color.White;ClientSize=new Size(500,470);StartPosition=FormStartPosition.CenterParent;Font=new Font("Segoe UI",9F);_headingLabel.AutoSize=true;_headingLabel.Font=new Font("Segoe UI",19F,FontStyle.Bold);_headingLabel.Location=new Point(38,32);_subtitleLabel.ForeColor=Color.FromArgb(107,114,128);_subtitleLabel.Location=new Point(41,78);_subtitleLabel.Size=new Size(410,52);_usernameLabel.AutoSize=true;_usernameLabel.Font=new Font("Segoe UI",9F,FontStyle.Bold);_usernameLabel.Location=new Point(41,135);_usernameLabel.Text="Username";_username.Location=new Point(44,159);_username.Size=new Size(408,30);_username.Font=new Font("Segoe UI",10F);_passwordLabel.AutoSize=true;_passwordLabel.Font=new Font("Segoe UI",9F,FontStyle.Bold);_passwordLabel.Location=new Point(41,211);_passwordLabel.Text="New password";_password.Location=new Point(44,235);_password.Size=new Size(408,30);_password.UseSystemPasswordChar=true;_password.Font=new Font("Segoe UI",10F);_confirmLabel.AutoSize=true;_confirmLabel.Font=new Font("Segoe UI",9F,FontStyle.Bold);_confirmLabel.Location=new Point(41,287);_confirmLabel.Text="Confirm password";_confirm.Location=new Point(44,311);_confirm.Size=new Size(408,30);_confirm.UseSystemPasswordChar=true;_confirm.Font=new Font("Segoe UI",10F);_error.ForeColor=Color.FromArgb(198,40,40);_error.Location=new Point(44,354);_error.Size=new Size(408,36);_saveButton.BackColor=Color.FromArgb(30,136,229);_saveButton.ForeColor=Color.White;_saveButton.FlatStyle=FlatStyle.Flat;_saveButton.FlatAppearance.BorderSize=0;_saveButton.Font=new Font("Segoe UI",9.5F,FontStyle.Bold);_saveButton.Location=new Point(282,407);_saveButton.Size=new Size(170,42);_saveButton.Click+=Save_Click;Controls.AddRange(new Control[]{_headingLabel,_subtitleLabel,_usernameLabel,_username,_passwordLabel,_password,_confirmLabel,_confirm,_error,_saveButton});AcceptButton=_saveButton;ResumeLayout(false);PerformLayout();}
    }
}
