using System.Drawing;
using System.Windows.Forms;

namespace JCGAttendanceSystem.Forms.Students
{
    partial class StudentEditorForm
    {
        private TableLayoutPanel _layout;
        private Panel _studentNumberPanel;
        private Label _studentNumberLabel;
        private TextBox _studentNumber;
        private Panel _rfidPanel;
        private Label _rfidLabel;
        private TextBox _rfidTag;
        private Panel _firstNamePanel;
        private Label _firstNameLabel;
        private TextBox _firstName;
        private Panel _lastNamePanel;
        private Label _lastNameLabel;
        private TextBox _lastName;
        private Panel _birthPanel;
        private Label _birthLabel;
        private DateTimePicker _birthDate;
        private Panel _genderPanel;
        private Label _genderLabel;
        private ComboBox _gender;
        private Panel _emailPanel;
        private Label _emailLabel;
        private TextBox _email;
        private Panel _coursePanel;
        private Label _courseLabel;
        private ComboBox _course;
        private Panel _yearPanel;
        private Label _yearLabel;
        private NumericUpDown _year;
        private Panel _sectionPanel;
        private Label _sectionLabel;
        private TextBox _section;
        private Label _error;
        private FlowLayoutPanel _actions;
        private Button _saveButton;
        private Button _cancelButton;

        private void InitializeComponent()
        {
            this._layout = new TableLayoutPanel();
            this._studentNumberPanel = new Panel();
            this._studentNumberLabel = new Label();
            this._studentNumber = new TextBox();
            this._rfidPanel = new Panel();
            this._rfidLabel = new Label();
            this._rfidTag = new TextBox();
            this._firstNamePanel = new Panel();
            this._firstNameLabel = new Label();
            this._firstName = new TextBox();
            this._lastNamePanel = new Panel();
            this._lastNameLabel = new Label();
            this._lastName = new TextBox();
            this._birthPanel = new Panel();
            this._birthLabel = new Label();
            this._birthDate = new DateTimePicker();
            this._genderPanel = new Panel();
            this._genderLabel = new Label();
            this._gender = new ComboBox();
            this._emailPanel = new Panel();
            this._emailLabel = new Label();
            this._email = new TextBox();
            this._coursePanel = new Panel();
            this._courseLabel = new Label();
            this._course = new ComboBox();
            this._yearPanel = new Panel();
            this._yearLabel = new Label();
            this._year = new NumericUpDown();
            this._sectionPanel = new Panel();
            this._sectionLabel = new Label();
            this._section = new TextBox();
            this._error = new Label();
            this._actions = new FlowLayoutPanel();
            this._saveButton = new Button();
            this._cancelButton = new Button();
            ((System.ComponentModel.ISupportInitialize)(this._year)).BeginInit();
            this.SuspendLayout();
            this._layout.Dock = DockStyle.Fill;
            this._layout.Padding = new Padding(30, 24, 30, 24);
            this._layout.ColumnCount = 2;
            this._layout.RowCount = 7;
            this._layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            this._layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            this._layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 84F));
            this._layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 84F));
            this._layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 84F));
            this._layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 84F));
            this._layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 84F));
            this._layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 55F));
            this._layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            // Student number
            this._studentNumberPanel.Dock = DockStyle.Fill;
            this._studentNumberPanel.Margin = new Padding(8, 4, 8, 4);
            this._studentNumberLabel.Dock = DockStyle.Top;
            this._studentNumberLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            this._studentNumberLabel.Height = 26;
            this._studentNumberLabel.Text = "Student Number *";
            this._studentNumber.Dock = DockStyle.Top;
            this._studentNumber.Font = new Font("Segoe UI", 10F);
            this._studentNumberPanel.Controls.Add(this._studentNumber);
            this._studentNumberPanel.Controls.Add(this._studentNumberLabel);
            // RFID
            this._rfidPanel.Dock = DockStyle.Fill;
            this._rfidPanel.Margin = new Padding(8, 4, 8, 4);
            this._rfidLabel.Dock = DockStyle.Top;
            this._rfidLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            this._rfidLabel.Height = 26;
            this._rfidLabel.Text = "RFID Tag";
            this._rfidTag.Dock = DockStyle.Top;
            this._rfidTag.Font = new Font("Segoe UI", 10F);
            this._rfidPanel.Controls.Add(this._rfidTag);
            this._rfidPanel.Controls.Add(this._rfidLabel);
            // first name
            this._firstNamePanel.Dock = DockStyle.Fill;
            this._firstNamePanel.Margin = new Padding(8, 4, 8, 4);
            this._firstNameLabel.Dock = DockStyle.Top;
            this._firstNameLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            this._firstNameLabel.Height = 26;
            this._firstNameLabel.Text = "First Name *";
            this._firstName.Dock = DockStyle.Top;
            this._firstName.Font = new Font("Segoe UI", 10F);
            this._firstNamePanel.Controls.Add(this._firstName);
            this._firstNamePanel.Controls.Add(this._firstNameLabel);
            // last name
            this._lastNamePanel.Dock = DockStyle.Fill;
            this._lastNamePanel.Margin = new Padding(8, 4, 8, 4);
            this._lastNameLabel.Dock = DockStyle.Top;
            this._lastNameLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            this._lastNameLabel.Height = 26;
            this._lastNameLabel.Text = "Last Name *";
            this._lastName.Dock = DockStyle.Top;
            this._lastName.Font = new Font("Segoe UI", 10F);
            this._lastNamePanel.Controls.Add(this._lastName);
            this._lastNamePanel.Controls.Add(this._lastNameLabel);
            // birth
            this._birthPanel.Dock = DockStyle.Fill;
            this._birthPanel.Margin = new Padding(8, 4, 8, 4);
            this._birthLabel.Dock = DockStyle.Top;
            this._birthLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            this._birthLabel.Height = 26;
            this._birthLabel.Text = "Birth Date";
            this._birthDate.Dock = DockStyle.Top;
            this._birthDate.Font = new Font("Segoe UI", 10F);
            this._birthDate.Format = DateTimePickerFormat.Short;
            this._birthDate.ShowCheckBox = true;
            this._birthPanel.Controls.Add(this._birthDate);
            this._birthPanel.Controls.Add(this._birthLabel);
            // gender
            this._genderPanel.Dock = DockStyle.Fill;
            this._genderPanel.Margin = new Padding(8, 4, 8, 4);
            this._genderLabel.Dock = DockStyle.Top;
            this._genderLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            this._genderLabel.Height = 26;
            this._genderLabel.Text = "Gender";
            this._gender.Dock = DockStyle.Top;
            this._gender.DropDownStyle = ComboBoxStyle.DropDownList;
            this._gender.Font = new Font("Segoe UI", 10F);
            this._gender.Items.AddRange(new object[] { "", "Male", "Female", "Other / Prefer not to say" });
            this._genderPanel.Controls.Add(this._gender);
            this._genderPanel.Controls.Add(this._genderLabel);
            // email
            this._emailPanel.Dock = DockStyle.Fill;
            this._emailPanel.Margin = new Padding(8, 4, 8, 4);
            this._emailLabel.Dock = DockStyle.Top;
            this._emailLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            this._emailLabel.Height = 26;
            this._emailLabel.Text = "Email";
            this._email.Dock = DockStyle.Top;
            this._email.Font = new Font("Segoe UI", 10F);
            this._emailPanel.Controls.Add(this._email);
            this._emailPanel.Controls.Add(this._emailLabel);
            // course
            this._coursePanel.Dock = DockStyle.Fill;
            this._coursePanel.Margin = new Padding(8, 4, 8, 4);
            this._courseLabel.Dock = DockStyle.Top;
            this._courseLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            this._courseLabel.Height = 26;
            this._courseLabel.Text = "Course *";
            this._course.Dock = DockStyle.Top;
            this._course.DropDownStyle = ComboBoxStyle.DropDown;
            this._course.Font = new Font("Segoe UI", 10F);
            this._course.Items.AddRange(new object[] { "BSCS", "BSIT", "BSBA", "BSHM", "BEED" });
            this._coursePanel.Controls.Add(this._course);
            this._coursePanel.Controls.Add(this._courseLabel);
            // year
            this._yearPanel.Dock = DockStyle.Fill;
            this._yearPanel.Margin = new Padding(8, 4, 8, 4);
            this._yearLabel.Dock = DockStyle.Top;
            this._yearLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            this._yearLabel.Height = 26;
            this._yearLabel.Text = "Year Level *";
            this._year.Dock = DockStyle.Top;
            this._year.Font = new Font("Segoe UI", 10F);
            this._year.Minimum = 1;
            this._year.Maximum = 4;
            this._year.Value = 1;
            this._yearPanel.Controls.Add(this._year);
            this._yearPanel.Controls.Add(this._yearLabel);
            // section
            this._sectionPanel.Dock = DockStyle.Fill;
            this._sectionPanel.Margin = new Padding(8, 4, 8, 4);
            this._sectionLabel.Dock = DockStyle.Top;
            this._sectionLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            this._sectionLabel.Height = 26;
            this._sectionLabel.Text = "Section *";
            this._section.Dock = DockStyle.Top;
            this._section.Font = new Font("Segoe UI", 10F);
            this._sectionPanel.Controls.Add(this._section);
            this._sectionPanel.Controls.Add(this._sectionLabel);
            this._layout.Controls.Add(this._studentNumberPanel, 0, 0);
            this._layout.Controls.Add(this._rfidPanel, 1, 0);
            this._layout.Controls.Add(this._firstNamePanel, 0, 1);
            this._layout.Controls.Add(this._lastNamePanel, 1, 1);
            this._layout.Controls.Add(this._birthPanel, 0, 2);
            this._layout.Controls.Add(this._genderPanel, 1, 2);
            this._layout.Controls.Add(this._emailPanel, 0, 3);
            this._layout.Controls.Add(this._coursePanel, 1, 3);
            this._layout.Controls.Add(this._yearPanel, 0, 4);
            this._layout.Controls.Add(this._sectionPanel, 1, 4);
            this._error.AutoSize = true;
            this._error.Font = new Font("Segoe UI", 9F);
            this._error.ForeColor = Color.FromArgb(198, 40, 40);
            this._error.Margin = new Padding(8, 10, 8, 0);
            this._layout.Controls.Add(this._error, 0, 5);
            this._layout.SetColumnSpan(this._error, 2);
            this._actions.Dock = DockStyle.Fill;
            this._actions.FlowDirection = FlowDirection.RightToLeft;
            this._actions.Padding = new Padding(0, 8, 4, 0);
            this._actions.WrapContents = false;
            this._saveButton.BackColor = Color.FromArgb(30, 136, 229);
            this._saveButton.FlatAppearance.BorderSize = 0;
            this._saveButton.FlatStyle = FlatStyle.Flat;
            this._saveButton.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            this._saveButton.ForeColor = Color.White;
            this._saveButton.Margin = new Padding(10, 0, 0, 0);
            this._saveButton.Size = new Size(140, 44);
            this._saveButton.Text = "Save Student";
            this._saveButton.Click += new System.EventHandler(this.Save_Click);
            this._cancelButton.BackColor = Color.White;
            this._cancelButton.FlatAppearance.BorderColor = Color.FromArgb(210, 218, 226);
            this._cancelButton.FlatStyle = FlatStyle.Flat;
            this._cancelButton.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            this._cancelButton.ForeColor = Color.FromArgb(31, 41, 55);
            this._cancelButton.Margin = new Padding(10, 0, 0, 0);
            this._cancelButton.Size = new Size(105, 44);
            this._cancelButton.Text = "Cancel";
            this._actions.Controls.Add(this._saveButton);
            this._actions.Controls.Add(this._cancelButton);
            this._layout.Controls.Add(this._actions, 0, 6);
            this._layout.SetColumnSpan(this._actions, 2);
            this.AcceptButton = this._saveButton;
            this.CancelButton = this._cancelButton;
            this.AutoScaleDimensions = new SizeF(7F, 15F);
            this.AutoScaleMode = AutoScaleMode.Font;
            this.BackColor = Color.White;
            this.ClientSize = new Size(720, 620);
            this.Controls.Add(this._layout);
            this.MinimumSize = new Size(660, 590);
            this.Name = "StudentEditorForm";
            this.StartPosition = FormStartPosition.CenterParent;
            ((System.ComponentModel.ISupportInitialize)(this._year)).EndInit();
            this.ResumeLayout(false);
        }
    }
}
